"""
Test Variables for Robot Framework
Generated by Agent 2 - Script Generator
"""

import os
from typing import Dict, Any

# Environment configuration
BASE_URL = os.getenv('BASE_URL', 'https://staging.example.com')
API_URL = os.getenv('API_URL', 'https://api-staging.example.com')
BROWSER = os.getenv('BROWSER', 'chromium')
HEADLESS = os.getenv('HEADLESS', 'True').lower() == 'true'

# Timeouts
DEFAULT_TIMEOUT = 30  # seconds
SHORT_TIMEOUT = 5
LONG_TIMEOUT = 60

# Test Data
VALID_USERS = {
    'standard': {
        'email': 'testuser@example.com',
        'password': 'ValidPass123!',
        'name': 'Test User',
    },
    'admin': {
        'email': 'admin@example.com',
        'password': 'AdminPass123!',
        'name': 'Admin User',
    },
}

INVALID_CREDENTIALS = {
    'wrong_password': {
        'email': 'testuser@example.com',
        'password': 'WrongPassword',
        'expected_error': 'Invalid credentials',
    },
    'wrong_email': {
        'email': 'nonexistent@example.com',
        'password': 'ValidPass123!',
        'expected_error': 'Invalid credentials',
    },
    'empty_email': {
        'email': '',
        'password': 'ValidPass123!',
        'expected_error': 'Email is required',
    },
    'empty_password': {
        'email': 'testuser@example.com',
        'password': '',
        'expected_error': 'Password is required',
    },
    'invalid_email_format': {
        'email': 'not-an-email',
        'password': 'ValidPass123!',
        'expected_error': 'Please enter a valid email address',
    },
}

# Product test data
TEST_PRODUCTS = [
    {'id': 'PROD-001', 'name': 'Basic Plan', 'price': 9.99, 'currency': 'USD'},
    {'id': 'PROD-002', 'name': 'Pro Plan', 'price': 29.99, 'currency': 'USD'},
    {'id': 'PROD-003', 'name': 'Enterprise Plan', 'price': 99.99, 'currency': 'USD'},
]

# Environment-specific configs
ENVIRONMENTS: Dict[str, Dict[str, Any]] = {
    'staging': {
        'base_url': 'https://staging.example.com',
        'api_url': 'https://api-staging.example.com',
        'database': 'staging_db',
    },
    'production': {
        'base_url': 'https://app.example.com',
        'api_url': 'https://api.example.com',
        'database': 'prod_db',
    },
    'development': {
        'base_url': 'http://localhost:3000',
        'api_url': 'http://localhost:8000',
        'database': 'dev_db',
    },
}

# Browser configurations
BROWSER_CONFIGS = {
    'chromium': {
        'browser_name': 'chromium',
        'channel': 'chrome',
        'args': ['--disable-web-security', '--disable-features=IsolateOrigins'],
    },
    'firefox': {
        'browser_name': 'firefox',
        'args': ['-private'],
    },
    'webkit': {
        'browser_name': 'webkit',
        'args': [],
    },
}

# Selectors (data-testid based for stability)
SELECTORS = {
    'login': {
        'email_input': 'data-testid=email-input',
        'password_input': 'data-testid=password-input',
        'remember_me': 'data-testid=remember-me',
        'login_button': 'data-testid=login-button',
        'forgot_password': 'data-testid=forgot-password-link',
        'signup_link': 'data-testid=signup-link',
        'error_message': 'data-testid=login-error',
        'success_message': 'data-testid=login-success',
        'page_title': 'data-testid=login-page-title',
        'logo': 'data-testid=logo',
        'email_validation_error': 'data-testid=email-validation-error',
        'password_validation_error': 'data-testid=password-validation-error',
    },
    'dashboard': {
        'welcome_message': 'data-testid=welcome-message',
        'user_menu': 'data-testid=user-menu',
        'user_menu_button': 'data-testid=user-menu-button',
        'logout_button': 'data-testid=logout-button',
        'profile_link': 'data-testid=profile-link',
        'settings_link': 'data-testid=settings-link',
        'nav_menu': 'data-testid=nav-menu',
        'nav_item': 'data-testid=nav-item',
        'stats_card': 'data-testid=stats-card',
        'stats_label': 'data-testid=stats-label',
        'stats_value': 'data-testid=stats-value',
        'recent_activity': 'data-testid=recent-activity',
        'quick_actions': 'data-testid=quick-actions',
    },
}

# API endpoints
API_ENDPOINTS = {
    'login': '/api/auth/login',
    'logout': '/api/auth/logout',
    'register': '/api/auth/register',
    'forgot_password': '/api/auth/forgot-password',
    'reset_password': '/api/auth/reset-password',
    'users': '/api/users',
    'products': '/api/products',
    'orders': '/api/orders',
}

# Test tags for filtering
TEST_TAGS = {
    'smoke': ['login', 'logout', 'navigation'],
    'regression': ['login', 'dashboard', 'profile', 'settings', 'products'],
    'critical': ['login', 'payment', 'security'],
    'high': ['login', 'registration', 'password-reset'],
    'medium': ['profile', 'settings', 'navigation'],
    'low': ['ui', 'accessibility', 'visual'],
    'negative': ['validation', 'error-handling', 'boundary'],
    'security': ['authentication', 'authorization', 'injection', 'xss'],
    'performance': ['load-time', 'response-time', 'memory'],
    'cross-browser': ['chromium', 'firefox', 'webkit'],
}

def get_environment_config(env: str = None) -> Dict[str, Any]:
    """Get configuration for specific environment."""
    env = env or os.getenv('ENVIRONMENT', 'staging')
    return ENVIRONMENTS.get(env, ENVIRONMENTS['staging'])

def get_browser_config(browser: str = None) -> Dict[str, Any]:
    """Get configuration for specific browser."""
    browser = browser or BROWSER
    return BROWSER_CONFIGS.get(browser, BROWSER_CONFIGS['chromium'])

def get_selectors(page: str) -> Dict[str, str]:
    """Get selectors for a specific page."""
    return SELECTORS.get(page, {})

def get_api_endpoint(endpoint: str) -> str:
    """Get full API endpoint URL."""
    return f"{API_URL}{API_ENDPOINTS.get(endpoint, '')}"