#!/usr/bin/env python3
"""
Create Jira user stories for the saucedemo STLC run (SCRUM project).
Stories describe the 6 user personas + negative login; known app defects
are filed as Tasks (Agent 4 failure-analysis output).
"""
import httpx

from config.settings import get_settings

s = get_settings()
AUTH = (s.jira_email, s.jira_api_token.get_secret_value())
BASE = s.jira_base_url.rstrip("/")

STORY_TYPE_ID = "10004"  # Story
TASK_TYPE_ID = "10003"   # Task (project has no Bug type)

PROJECT = s.jira_project_key


def adf(text: str) -> dict:
    """Wrap plain text in Atlassian Document Format."""
    return {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": text}],
            }
        ],
    }


def create_issue(issue_type_id: str, summary: str, description: str, labels: list) -> str:
    payload = {
        "fields": {
            "project": {"key": PROJECT},
            "issuetype": {"id": issue_type_id},
            "summary": summary,
            "description": adf(description),
            "labels": labels,
        }
    }
    r = httpx.post(f"{BASE}/rest/api/3/issue", auth=AUTH, json=payload, timeout=30)
    if r.status_code in (200, 201):
        key = r.json()["key"]
        print(f"  created {key}: {summary[:70]}")
        return key
    print(f"  FAILED ({r.status_code}): {summary[:60]} -> {r.text[:200]}")
    return ""


STORIES = [
    {
        "summary": "As a standard user, I can log in and complete a full shopping journey on Swag Labs",
        "description": (
            "User Story (generated by Agent 1 - Test Case Author)\n\n"
            "Persona: standard_user / secret_sauce at https://www.saucedemo.com/\n\n"
            "Acceptance criteria:\n"
            "1. Valid login lands on the inventory (Products) page.\n"
            "2. Adding an item to the cart shows badge count 1.\n"
            "3. Checkout with first name, last name and postal code completes and shows 'Thank you'.\n"
            "4. Logout returns to the login screen.\n\n"
            "Automation: covered by tests/saucedemo_users.spec.ts and Agent 2 generated scripts."
        ),
        "labels": ["stlc", "agent-generated", "standard_user"],
    },
    {
        "summary": "As a locked-out user, my login attempt is blocked with a clear error",
        "description": (
            "User Story (generated by Agent 1 - Test Case Author)\n\n"
            "Persona: locked_out_user / secret_sauce at https://www.saucedemo.com/\n\n"
            "Acceptance criteria:\n"
            "1. Login is rejected and stays on the login page.\n"
            "2. Error banner shows 'Epic sadface: Sorry, this user has been locked out.'\n"
            "3. Banner can be dismissed with the close (X) button.\n\n"
            "Automation: covered by tests/saucedemo_users.spec.ts."
        ),
        "labels": ["stlc", "agent-generated", "locked_out_user"],
    },
    {
        "summary": "As a user with connection issues, I can still log in and see the inventory (problem_user)",
        "description": (
            "User Story (generated by Agent 1 - Test Case Author)\n\n"
            "Persona: problem_user / secret_sauce at https://www.saucedemo.com/\n\n"
            "Acceptance criteria:\n"
            "1. Login succeeds and lands on the inventory page.\n"
            "2. KNOWN DEFECT: the first product image fails to load (broken image on inventory).\n"
            "   See defect ticket filed for the broken image.\n\n"
            "Automation: covered by tests/saucedemo_users.spec.ts (logs image natural width)."
        ),
        "labels": ["stlc", "agent-generated", "problem_user"],
    },
    {
        "summary": "As a user on a slow connection, login works despite the delay (performance_glitch_user)",
        "description": (
            "User Story (generated by Agent 1 - Test Case Author)\n\n"
            "Persona: performance_glitch_user / secret_sauce at https://www.saucedemo.com/\n\n"
            "Acceptance criteria:\n"
            "1. Login eventually succeeds and lands on the inventory page.\n"
            "2. Login takes noticeably longer than standard_user (seconds, not milliseconds).\n"
            "3. No timeout or error is shown.\n\n"
            "Automation: covered by tests/saucedemo_users.spec.ts (annotates login_ms)."
        ),
        "labels": ["stlc", "agent-generated", "performance_glitch_user"],
    },
    {
        "summary": "As an error user, I can log in and browse products (error_user)",
        "description": (
            "User Story (generated by Agent 1 - Test Case Author)\n\n"
            "Persona: error_user / secret_sauce at https://www.saucedemo.com/\n\n"
            "Acceptance criteria:\n"
            "1. Login succeeds and lands on the inventory page.\n"
            "2. KNOWN DEFECT: checkout/save steps can error for this persona (documented by the app authors).\n\n"
            "Automation: covered by tests/saucedemo_users.spec.ts."
        ),
        "labels": ["stlc", "agent-generated", "error_user"],
    },
    {
        "summary": "As a visual user, I can log in and browse products (visual_user)",
        "description": (
            "User Story (generated by Agent 1 - Test Case Author)\n\n"
            "Persona: visual_user / secret_sauce at https://www.saucedemo.com/\n\n"
            "Acceptance criteria:\n"
            "1. Login succeeds and lands on the inventory page.\n"
            "2. KNOWN DEFECT: visual mismatches exist on inventory elements for this persona "
            "(documented by the app authors).\n\n"
            "Automation: covered by tests/saucedemo_users.spec.ts."
        ),
        "labels": ["stlc", "agent-generated", "visual_user"],
    },
    {
        "summary": "As a user, invalid credentials show a clear, dismissible error (negative login)",
        "description": (
            "User Story (generated by Agent 1 - Test Case Author)\n\n"
            "Scope: negative login validation at https://www.saucedemo.com/\n\n"
            "Acceptance criteria:\n"
            "1. Wrong password shows 'Epic sadface: Username and password do not match any user in this service'.\n"
            "2. Empty username/password are rejected with error banners.\n"
            "3. Every error banner has a close (X) button that dismisses it.\n\n"
            "Automation: covered by both generated suites."
        ),
        "labels": ["stlc", "agent-generated", "negative"],
    },
]

DEFECTS = [
    {
        "summary": "[Agent 4] problem_user: first inventory product image fails to load",
        "description": (
            "Defect filed by Agent 4 - Failure Analyst (Agentic STLC pipeline)\n\n"
            "Classification: Product Bug\n"
            "Severity: Minor\nEnvironment: staging / chromium\n"
            "Source run: saucedemo-e2e-20260926 (GitHub Actions run 36241060307)\n\n"
            "Steps to reproduce:\n"
            "1. Open https://www.saucedemo.com/\n"
            "2. Log in as problem_user / secret_sauce\n"
            "3. Observe the first product card image\n\n"
            "Expected: product image (backpack) renders.\n"
            "Actual: broken image placeholder; img naturalWidth is 0.\n\n"
            "Evidence: tests/saucedemo_users.spec.ts 'login as problem_user' "
            "annotates first_image_natural_width=0."
        ),
        "labels": ["bug", "agent-generated", "problem_user"],
    },
    {
        "summary": "[Agent 4] CI: generated tests used nonexistent data-testid selectors (healed)",
        "description": (
            "Defect filed by Agent 4 - Failure Analyst (Agentic STLC pipeline)\n\n"
            "Classification: Test Script Issue (self-healed)\n"
            "Severity: Major\nEnvironment: GitHub Actions / chromium, firefox, webkit\n"
            "Source run: 36241060307\n\n"
            "Failure: 3 tests failed waiting for getByTestId('login-page-title') - "
            "the saucedemo app has no data-testid attributes.\n\n"
            "Root cause: Agent 2 generated selectors from a generic template instead of "
            "the real DOM. Self-healing (Stage 4 -> Stage 3 loop) replaced page objects "
            "with real locators; suites re-verified green locally (18/18).\n\n"
            "Recommended action: none - healed; ticket kept for traceability."
        ),
        "labels": ["bug", "agent-generated", "self-healed"],
    },
]


def main():
    print("Creating user stories (Agent 1 output):")
    story_keys = []
    for st in STORIES:
        key = create_issue(STORY_TYPE_ID, st["summary"], st["description"], st["labels"])
        if key:
            story_keys.append(key)

    print("Creating defect tasks (Agent 4 output):")
    defect_keys = []
    for d in DEFECTS:
        key = create_issue(TASK_TYPE_ID, d["summary"], d["description"], d["labels"])
        if key:
            defect_keys.append(key)

    print()
    print(f"Created {len(story_keys)} stories and {len(defect_keys)} defects:")
    print("Stories:", ", ".join(story_keys))
    print("Defects:", ", ".join(defect_keys))


if __name__ == "__main__":
    main()
