/**
 * Dashboard Page Object Model
 * 
 * Generated by Agent 2 - Script Generator
 */

import { Page, Locator, expect } from '@playwright/test';

export class DashboardPage {
  readonly page: Page;
  readonly url = '/dashboard';
  
  // Header elements
  readonly welcomeMessage: Locator;
  readonly userMenu: Locator;
  readonly userMenuButton: Locator;
  readonly logoutButton: Locator;
  readonly profileLink: Locator;
  readonly settingsLink: Locator;
  
  // Navigation
  readonly navMenu: Locator;
  readonly navItems: Locator;
  
  // Content areas
  readonly statsCards: Locator;
  readonly recentActivity: Locator;
  readonly quickActions: Locator;

  constructor(page: Page) {
    this.page = page;
    
    this.welcomeMessage = page.getByTestId('welcome-message');
    this.userMenu = page.getByTestId('user-menu');
    this.userMenuButton = page.getByTestId('user-menu-button');
    this.logoutButton = page.getByTestId('logout-button');
    this.profileLink = page.getByTestId('profile-link');
    this.settingsLink = page.getByTestId('settings-link');
    this.navMenu = page.getByTestId('nav-menu');
    this.navItems = page.getByTestId('nav-item');
    this.statsCards = page.getByTestId('stats-card');
    this.recentActivity = page.getByTestId('recent-activity');
    this.quickActions = page.getByTestId('quick-actions');
  }

  /**
   * Navigate to dashboard and wait for load
   */
  async goto(): Promise<void> {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('networkidle');
    await expect(this.welcomeMessage).toBeVisible();
  }

  /**
   * Expect user is logged in with specific name
   */
  async expectLoggedIn(username: string): Promise<void> {
    await expect(this.welcomeMessage).toBeVisible();
    await expect(this.welcomeMessage).toContainText(username);
  }

  /**
   * Open user menu
   */
  async openUserMenu(): Promise<void> {
    await this.userMenuButton.click();
    await expect(this.userMenu).toBeVisible();
  }

  /**
   * Logout from dashboard
   */
  async logout(): Promise<void> {
    await this.openUserMenu();
    await this.logoutButton.click();
    await this.page.waitForURL(/\/login/);
  }

  /**
   * Navigate to profile page
   */
  async goToProfile(): Promise<void> {
    await this.openUserMenu();
    await this.profileLink.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Navigate to settings page
   */
  async goToSettings(): Promise<void> {
    await this.openUserMenu();
    await this.settingsLink.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Click navigation item by text
   */
  async clickNavItem(itemText: string): Promise<void> {
    const navItem = this.navItems.filter({ hasText: itemText });
    await navItem.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Get stats card values
   */
  async getStats(): Promise<Record<string, string>> {
    const cards = await this.statsCards.all();
    const stats: Record<string, string> = {};
    
    for (const card of cards) {
      const label = await card.getByTestId('stats-label').textContent();
      const value = await card.getByTestId('stats-value').textContent();
      if (label && value) {
        stats[label.trim()] = value.trim();
      }
    }
    
    return stats;
  }

  // ============================================================================
  // Assertions
  // ============================================================================

  /**
   * Expect dashboard to be loaded
   */
  async expectDashboardLoaded(): Promise<void> {
    await expect(this.welcomeMessage).toBeVisible();
    await expect(this.navMenu).toBeVisible();
  }

  /**
   * Expect specific stats values
   */
  async expectStats(expectedStats: Record<string, string>): Promise<void> {
    const actualStats = await this.getStats();
    for (const [key, expectedValue] of Object.entries(expectedStats)) {
      expect(actualStats[key]).toBe(expectedValue);
    }
  }

  // ============================================================================
  // Helper methods for self-healing
  // ============================================================================

  /**
   * Get all interactive elements for MCP healing analysis
   */
  async getInteractiveElements(): Promise<Record<string, string>> {
    return {
      userMenuButton: await this.userMenuButton.getAttribute('data-testid') || '',
      logoutButton: await this.logoutButton.getAttribute('data-testid') || '',
      profileLink: await this.profileLink.getAttribute('data-testid') || '',
      settingsLink: await this.settingsLink.getAttribute('data-testid') || '',
    };
  }

  /**
   * Get current DOM snapshot for healing
   */
  async getDOMSnapshot(): Promise<string> {
    return await this.page.content();
  }
}