/**
 * Login Page Object Model
 * 
 * Generated by Agent 2 - Script Generator
 * Uses data-testid selectors for stability and MCP self-healing compatibility.
 */

import { Page, Locator, expect } from '@playwright/test';

export class LoginPage {
  readonly page: Page;
  readonly url = '/login';
  
  // Form fields - using data-testid for stable selectors
  readonly emailInput: Locator;
  readonly passwordInput: Locator;
  readonly rememberMeCheckbox: Locator;
  readonly loginButton: Locator;
  
  // Links
  readonly forgotPasswordLink: Locator;
  readonly signupLink: Locator;
  
  // Messages
  readonly errorMessage: Locator;
  readonly successMessage: Locator;
  
  // Page elements
  readonly pageTitle: Locator;
  readonly logo: Locator;

  constructor(page: Page) {
    this.page = page;
    
    // Initialize locators with data-testid (preferred)
    this.emailInput = page.getByTestId('email-input');
    this.passwordInput = page.getByTestId('password-input');
    this.rememberMeCheckbox = page.getByTestId('remember-me');
    this.loginButton = page.getByTestId('login-button');
    this.forgotPasswordLink = page.getByTestId('forgot-password-link');
    this.signupLink = page.getByTestId('signup-link');
    this.errorMessage = page.getByTestId('login-error');
    this.successMessage = page.getByTestId('login-success');
    this.pageTitle = page.getByTestId('login-page-title');
    this.logo = page.getByTestId('logo');
  }

  /**
   * Navigate to login page and wait for load
   */
  async goto(): Promise<void> {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('networkidle');
    await expect(this.pageTitle).toBeVisible();
  }

  /**
   * Fill login form
   */
  async fillForm(email: string, password: string): Promise<void> {
    await this.emailInput.fill(email);
    await this.passwordInput.fill(password);
  }

  /**
   * Toggle remember me checkbox
   */
  async setRememberMe(checked: boolean): Promise<void> {
    if (checked) {
      await this.rememberMeCheckbox.check();
    } else {
      await this.rememberMeCheckbox.uncheck();
    }
  }

  /**
   * Submit login form
   */
  async submit(): Promise<void> {
    await this.loginButton.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Complete login flow
   */
  async login(email: string, password: string, rememberMe = false): Promise<void> {
    await this.fillForm(email, password);
    if (rememberMe) {
      await this.setRememberMe(true);
    }
    await this.submit();
  }

  /**
   * Click forgot password link
   */
  async clickForgotPassword(): Promise<void> {
    await this.forgotPasswordLink.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Click signup link
   */
  async clickSignup(): Promise<void> {
    await this.signupLink.click();
    await this.page.waitForLoadState('networkidle');
  }

  // ============================================================================
  // Assertions
  // ============================================================================

  /**
   * Expect error message to be visible with specific text
   */
  async expectErrorMessage(message: string): Promise<void> {
    await expect(this.errorMessage).toBeVisible();
    await expect(this.errorMessage).toContainText(message);
  }

  /**
   * Expect success message
   */
  async expectSuccessMessage(message: string): Promise<void> {
    await expect(this.successMessage).toBeVisible();
    await expect(this.successMessage).toContainText(message);
  }

  /**
   * Expect email input to have validation error
   */
  async expectEmailValidationError(message: string): Promise<void> {
    await expect(this.emailInput).toHaveAttribute('aria-invalid', 'true');
    // Check for inline validation message
    const inlineError = this.page.getByTestId('email-validation-error');
    await expect(inlineError).toBeVisible();
    await expect(inlineError).toContainText(message);
  }

  /**
   * Expect password input to have validation error
   */
  async expectPasswordValidationError(message: string): Promise<void> {
    await expect(this.passwordInput).toHaveAttribute('aria-invalid', 'true');
    const inlineError = this.page.getByTestId('password-validation-error');
    await expect(inlineError).toBeVisible();
    await expect(inlineError).toContainText(message);
  }

  /**
   * Expect login button to be disabled
   */
  async expectLoginDisabled(): Promise<void> {
    await expect(this.loginButton).toBeDisabled();
  }

  /**
   * Expect login button to be enabled
   */
  async expectLoginEnabled(): Promise<void> {
    await expect(this.loginButton).toBeEnabled();
  }

  /**
   * Expect page to be on login URL
   */
  async expectOnLoginPage(): Promise<void> {
    await expect(this.page).toHaveURL(/\/login/);
  }

  // ============================================================================
  // Helper methods for self-healing
  // ============================================================================

  /**
   * Get all interactive elements for MCP healing analysis
   */
  async getInteractiveElements(): Promise<Record<string, string>> {
    return {
      emailInput: await this.emailInput.getAttribute('data-testid') || '',
      passwordInput: await this.passwordInput.getAttribute('data-testid') || '',
      loginButton: await this.loginButton.getAttribute('data-testid') || '',
      rememberMeCheckbox: await this.rememberMeCheckbox.getAttribute('data-testid') || '',
      forgotPasswordLink: await this.forgotPasswordLink.getAttribute('data-testid') || '',
      signupLink: await this.signupLink.getAttribute('data-testid') || '',
    };
  }

  /**
   * Get current DOM snapshot for healing
   */
  async getDOMSnapshot(): Promise<string> {
    return await this.page.content();
  }
}