/**
 * Playwright Sample Test Suite - saucedemo.com
 *
 * Generated by Agent 2 - Script Generator; selectors healed by Agent 2b.
 * Locators match the real saucedemo DOM: #user-name, #password,
 * #login-button, [data-test=error], .inventory_list.
 *
 * Run with: npx playwright test tests/e2e_sample.spec.ts
 */

import { test, expect } from '@playwright/test';
import { LoginPage } from './pages/LoginPage';
import { InventoryPage } from './pages/InventoryPage';

// ============================================================================
// Test Configuration
// ============================================================================

test.describe.configure({ retries: 2 });

// ============================================================================
// Test Data (saucedemo accepted users)
// ============================================================================

const PASSWORD = 'secret_sauce';

const testCases = [
  {
    id: 'TC-LOGIN-001',
    title: 'Valid user login',
    priority: 'Critical',
    user: 'standard_user',
    shouldSucceed: true,
    expectedResult: 'User redirected to inventory',
  },
  {
    id: 'TC-LOGIN-002',
    title: 'Invalid password shows error',
    priority: 'High',
    user: 'standard_user',
    passwordOverride: 'wrong_password',
    shouldSucceed: false,
    expectedError: 'Username and password do not match',
  },
  {
    id: 'TC-LOGIN-003',
    title: 'Locked out user is blocked',
    priority: 'High',
    user: 'locked_out_user',
    shouldSucceed: false,
    expectedError: 'locked out',
  },
];

// ============================================================================
// Test Cases
// ============================================================================

test.describe('User Authentication', () => {

  testCases.forEach(({ id, title, priority, user, passwordOverride, shouldSucceed, expectedError }) => {
    test(`[${id}] ${title}`, async ({ page }) => {
      test.info().annotations.push({ type: 'priority', description: priority });

      const loginPage = new LoginPage(page);
      const inventoryPage = new InventoryPage(page);

      await loginPage.goto();
      await loginPage.login(user, passwordOverride ?? PASSWORD);

      if (shouldSucceed) {
        await inventoryPage.expectLoaded();
        await inventoryPage.logout();
      } else {
        await loginPage.expectErrorMessage(expectedError ?? '');
      }
    });
  });

});

// ============================================================================
// Data-Driven Tests
// ============================================================================

test.describe('Data-Driven Login Tests', () => {
  const loginData = [
    { user: 'standard_user', password: 'wrong_pass', shouldPass: false },
    { user: '', password: 'secret_sauce', shouldPass: false },
    { user: 'standard_user', password: '', shouldPass: false },
    { user: 'problem_user', password: 'secret_sauce', shouldPass: true },
    { user: 'error_user', password: 'secret_sauce', shouldPass: true },
  ];

  for (const data of loginData) {
    test(`Login with ${data.user || 'empty username'} / ${data.password ? 'provided password' : 'empty password'}`, async ({ page }) => {
      const loginPage = new LoginPage(page);
      const inventoryPage = new InventoryPage(page);

      await loginPage.goto();
      await loginPage.login(data.user, data.password);

      if (data.shouldPass) {
        await inventoryPage.expectLoaded();
        await inventoryPage.logout();
      } else {
        await expect(loginPage.errorMessage).toBeVisible();
      }
    });
  }
});

// ============================================================================
// Performance Tests
// ============================================================================

test.describe('Performance', () => {
  test('Login page loads within 3 seconds', async ({ page }) => {
    const startTime = Date.now();
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    const loadTime = Date.now() - startTime;

    expect(loadTime).toBeLessThan(3000);
  });

  test('performance_glitch_user login completes (with delay)', async ({ page }) => {
    const loginPage = new LoginPage(page);
    const inventoryPage = new InventoryPage(page);
    const startTime = Date.now();

    await loginPage.goto();
    await loginPage.login('performance_glitch_user', PASSWORD);
    await inventoryPage.expectLoaded();

    const elapsed = Date.now() - startTime;
    test.info().annotations.push({ type: 'login_ms', description: String(elapsed) });
  });
});
