*** Settings ***
Documentation     Robot Framework Sample Test Suite for Agentic AI STLC Pipeline
...               Generated by Agent 2 - Script Generator
...               Supports both Playwright and Robot Framework execution

Library           Browser
Library           Collections
Library           String

Resource          ../resources/common.keywords.robot
Variables         ../variables/test_variables.py

*** Variables ***
${BASE_URL}       https://staging.example.com
${BROWSER}        chromium
${HEADLESS}       True
${TIMEOUT}        30s
${IMPLICIT_WAIT}  5s

# Test Data
@{VALID_USERS}    testuser@example.com    ValidPass123!    Test User
@{INVALID_USERS}  testuser@example.com    WrongPass        Test User
@{INVALID_EMAILS} not-an-email            ValidPass123!    Test User

*** Test Cases ***

TC-LOGIN-001 Valid User Login
    [Documentation]    Test successful login with valid credentials
    [Tags]             critical    login    smoke    regression
    [Setup]            Open Login Page
    Login              ${VALID_USERS[0]}    ${VALID_USERS[1]}
    Verify Dashboard   ${VALID_USERS[2]}
    [Teardown]         Logout And Close Browser

TC-LOGIN-002 Invalid Password Shows Error
    [Documentation]    Test login failure with incorrect password
    [Tags]             high    login    negative    regression
    [Setup]            Open Login Page
    Login              ${INVALID_USERS[0]}    ${INVALID_USERS[1]}
    Verify Error       ${INVALID_USERS[3]}
    [Teardown]         Close Browser

TC-LOGIN-003 Invalid Email Format Shows Error
    [Documentation]    Test login failure with invalid email format
    [Tags]             medium    login    negative    validation
    [Setup]            Open Login Page
    Login              ${INVALID_EMAILS[0]}    ${INVALID_EMAILS[1]}
    Verify Error       ${INVALID_EMAILS[3]}
    [Teardown]         Close Browser

TC-LOGIN-004 Empty Email Field Validation
    [Documentation]    Test validation when email field is empty
    [Tags]             medium    login    validation    negative
    [Setup]            Open Login Page
    Fill Email Field
    Fill Password Field    ValidPass123!
    Click Login Button
    Verify Inline Validation    email    Email is required
    [Teardown]         Close Browser

TC-LOGIN-005 Empty Password Field Validation
    [Documentation]    Test validation when password field is empty
    [Tags]             medium    login    validation    negative
    [Setup]            Open Login Page
    Fill Email Field    testuser@example.com
    Fill Password Field
    Click Login Button
    Verify Inline Validation    password    Password is required
    [Teardown]         Close Browser

TC-LOGIN-006 Remember Me Functionality
    [Documentation]    Test remember me checkbox persists session
    [Tags]             low    login    remember-me    functional
    [Setup]            Open Login Page
    Login              ${VALID_USERS[0]}    ${VALID_USERS[1]}    True
    Verify Dashboard   ${VALID_USERS[2]}
    Close Browser
    # Reopen browser - session should persist
    Open Browser To Login Page
    Verify Dashboard   ${VALID_USERS[2]}
    [Teardown]         Logout And Close Browser

TC-LOGIN-007 Forgot Password Flow
    [Documentation]    Test forgot password link navigation
    [Tags]             medium    login    forgot-password    functional
    [Setup]            Open Login Page
    Click Forgot Password Link
    Verify Page Title    Forgot Password
    [Teardown]         Close Browser

TC-LOGIN-008 Signup Link Navigation
    [Documentation]    Test signup link navigates to registration
    [Tags]             low    login    signup    navigation
    [Setup]            Open Login Page
    Click Signup Link
    Verify Page Title    Sign Up
    [Teardown]         Close Browser

TC-LOGIN-009 Multiple Failed Attempts Lock Account
    [Documentation]    Test account lockout after multiple failures
    [Tags]             high    login    security    lockout
    [Setup]            Open Login Page
    :FOR    ${i}    IN RANGE    5
    \    Login    ${VALID_USERS[0]}    WrongPassword
    \    Verify Error    Invalid credentials
    Login    ${VALID_USERS[0]}    ${VALID_USERS[1]}
    Verify Error    Account is locked
    [Teardown]         Close Browser

TC-LOGIN-010 Cross-Browser Login
    [Documentation]    Test login works across browsers
    [Tags]             medium    login    cross-browser    regression
    [Template]         Cross Browser Login Template
    chromium
    firefox
    webkit

*** Keywords ***

Open Login Page
    [Arguments]    ${url}=${BASE_URL}/login
    New Browser    ${BROWSER}    headless=${HEADLESS}
    New Context    viewport={'width': 1280, 'height': 720}
    New Page
    Go To    ${url}
    Wait For Load State    networkidle
    Page Should Contain Element    data-testid=login-page-title

Open Browser To Login Page
    Call Keyword    Open Login Page

Login
    [Arguments]    ${email}    ${password}    ${remember}=False
    Fill    data-testid=email-input    ${email}
    Fill    data-testid=password-input    ${password}
    Run Keyword If    ${remember}    Check    data-testid=remember-me
    Click    data-testid=login-button
    Wait For Load State    networkidle

Verify Dashboard
    [Arguments]    ${username}
    Page Should Contain Element    data-testid=welcome-message
    Element Should Contain    data-testid=welcome-message    ${username}

Verify Error
    [Arguments]    ${expected_error}
    Page Should Contain Element    data-testid=login-error
    Element Should Contain    data-testid=login-error    ${expected_error}

Verify Inline Validation
    [Arguments]    ${field}    ${expected_message}
    ${selector}=    Set Variable    data-testid=${field}-validation-error
    Page Should Contain Element    ${selector}
    Element Should Contain    ${selector}    ${expected_message}

Click Forgot Password Link
    Click    data-testid=forgot-password-link
    Wait For Load State    networkidle

Click Signup Link
    Click    data-testid=signup-link
    Wait For Load State    networkidle

Verify Page Title
    [Arguments]    ${expected_title}
    Title Should Be    ${expected_title}

Logout And Close Browser
    Click    data-testid=user-menu-button
    Click    data-testid=logout-button
    Wait For URL    */login
    Close Browser

Cross Browser Login Template
    [Arguments]    ${browser}
    Set Suite Variable    ${BROWSER}    ${browser}
    Call Keyword    Open Login Page
    Login    ${VALID_USERS[0]}    ${VALID_USERS[1]}
    Verify Dashboard    ${VALID_USERS[2]}
    [Teardown]    Logout And Close Browser

Fill Email Field
    [Arguments]    ${email}=
    Fill    data-testid=email-input    ${email}

Fill Password Field
    [Arguments]    ${password}=
    Fill    data-testid=password-input    ${password}

Click Login Button
    Click    data-testid=login-button
    Wait For Load State    networkidle